import React, { createContext, useContext, useState, useEffect } from 'react';
import { ACTIVE_LANGUAGES, INTERNATIONAL_LANGUAGES, INDIAN_LANGUAGES } from '../data/languages';

const LanguageContext = createContext();

const UI_TRANSLATIONS = {
  en: {
    brand_name: 'ItihAI',
    tagline: 'Understand the language, discover the culture',
    hero_subtitle: 'Your intelligent multilingual companion for discovering India\'s heritage, history and culture.',
    explore_heritage: 'Explore Heritage',
    ask_itihai: 'Ask ItihAI',
    start_journey: 'Start Your Journey',
    nav_home: 'Home',
    nav_explore: 'Explore',
    nav_guide: 'AI Guide',
    nav_languages: 'Languages',
    nav_about: 'About',
    featured_title: 'Explore India\'s Heritage',
    featured_subtitle: 'Discover timeless monuments, UNESCO World Heritage wonders, and living traditions.',
    how_it_works_title: 'How It Works',
    how_step1: 'Discover',
    how_step1_desc: 'Browse monuments by historical period, architectural style, and region.',
    how_step2: 'Ask',
    how_step2_desc: 'Ask questions in your native tongue using voice or text.',
    how_step3: 'Understand',
    how_step3_desc: 'Receive verified historical insights and cultural etiquette guidance.',
    how_step4: 'Explore',
    how_step4_desc: 'Immerse yourself with hands-free audio narration on the ground.',
    view_all_sites: 'View All Heritage Sites',
    search_placeholder: 'Search monuments, cities, historical dynasties...',
    all_regions: 'All Regions',
    all_periods: 'All Periods',
    all_types: 'All Categories',
    ask_about_monument: 'Ask ItihAI about this place',
    listen_audio_guide: 'Listen to Audio Narration',
    facts_title: 'Fascinating Facts',
    traditions_title: 'Local Customs & Etiquette',
    visiting_title: 'Practical Visitor Guide',
    nearby_title: 'Nearby Attractions',
    speak_your_lang_title: 'Explore India in Your Language',
    speak_your_lang_desc: 'Understand India\'s history, culture and traditions without the language barrier. Choose your language and let ItihAI guide your journey.',
    listen_learn_title: 'Listen & Learn with Voice Guides',
    demo_badge: 'Phase 2 UI Preview',
  },
  fr: {
    brand_name: 'ItihAI',
    tagline: 'Comprenez la langue, découvrez la culture',
    hero_subtitle: 'Votre guide multilingue intelligent pour explorer le patrimoine, l\'histoire et les traditions de l\'Inde.',
    explore_heritage: 'Explorer le patrimoine',
    ask_itihai: 'Demander à ItihAI',
    start_journey: 'Commencer le voyage',
    nav_home: 'Accueil',
    nav_explore: 'Explorer',
    nav_guide: 'Guide IA',
    nav_languages: 'Langues',
    nav_about: 'À propos',
    featured_title: 'Explorer le patrimoine de l\'Inde',
    featured_subtitle: 'Découvrez des monuments intemporels, des merveilles de l\'UNESCO et des traditions vivantes.',
    how_it_works_title: 'Comment ça marche',
    how_step1: 'Découvrir',
    how_step1_desc: 'Parcourez les monuments par époque historique, style architectural et région.',
    how_step2: 'Demander',
    how_step2_desc: 'Posez des questions dans votre langue maternelle par voix ou texte.',
    how_step3: 'Comprendre',
    how_step3_desc: 'Recevez des analyses historiques vérifiées et des conseils d\'étiquette culturelle.',
    how_step4: 'Explorer',
    how_step4_desc: 'Immergez-vous avec des narrations audio mains libres sur place.',
    view_all_sites: 'Voir tous les sites',
    search_placeholder: 'Rechercher des monuments, villes, dynasties...',
    all_regions: 'Toutes les régions',
    all_periods: 'Toutes les périodes',
    all_types: 'Toutes catégories',
    ask_about_monument: 'Poser une question sur ce monument',
    listen_audio_guide: 'Écouter la narration audio',
    facts_title: 'Faits fascinants',
    traditions_title: 'Coutumes et étiquette locales',
    visiting_title: 'Guide pratique du visiteur',
    nearby_title: 'Attractions à proximité',
    speak_your_lang_title: 'Explorez l\'Inde dans votre langue',
    speak_your_lang_desc: 'Comprenez l\'histoire, la culture et les traditions de l\'Inde sans barrière linguistique. Choisissez votre langue et laissez ItihAI guider votre voyage.',
    listen_learn_title: 'Écouter et apprendre avec les guides vocaux',
    demo_badge: 'Aperçu UI Phase 2',
  },
  de: {
    brand_name: 'ItihAI',
    tagline: 'Die Sprache verstehen, die Kultur entdecken',
    hero_subtitle: 'Ihr intelligenter mehrsprachiger Begleiter zur Entdeckung des indischen Kulturerbes und der Geschichte.',
    explore_heritage: 'Kulturerbe erkunden',
    ask_itihai: 'ItihAI fragen',
    start_journey: 'Reise beginnen',
    nav_home: 'Startseite',
    nav_explore: 'Erkunden',
    nav_guide: 'KI-Guide',
    nav_languages: 'Sprachen',
    nav_about: 'Über uns',
    featured_title: 'Indiens Kulturerbe erkunden',
    featured_subtitle: 'Entdecken Sie zeitlose Denkmäler, UNESCO-Welterbestätten und lebendige Traditionen.',
    how_it_works_title: 'So funktioniert es',
    how_step1: 'Entdecken',
    how_step1_desc: 'Durchsuchen Sie Denkmäler nach Epoche, Baustil und Region.',
    how_step2: 'Fragen',
    how_step2_desc: 'Stellen Sie Fragen in Ihrer Muttersprache per Sprache oder Text.',
    how_step3: 'Verstehen',
    how_step3_desc: 'Erhalten Sie geprüfte historische Einblicke und Verhaltensregeln.',
    how_step4: 'Erleben',
    how_step4_desc: 'Erleben Sie historische Stätten mit praktischen Audio-Guides vor Ort.',
    view_all_sites: 'Alle Stätten anzeigen',
    search_placeholder: 'Denkmäler, Städte, Dynastien suchen...',
    all_regions: 'Alle Regionen',
    all_periods: 'Alle Epochen',
    all_types: 'Alle Kategorien',
    ask_about_monument: 'ItihAI zu diesem Ort befragen',
    listen_audio_guide: 'Audio-Führung anhören',
    facts_title: 'Faszinierende Fakten',
    traditions_title: 'Lokale Bräuche & Etikette',
    visiting_title: 'Praktischer Besucher-Guide',
    nearby_title: 'Sehenswürdigkeiten in der Nähe',
    speak_your_lang_title: 'Erkunden Sie Indien in Ihrer Sprache',
    speak_your_lang_desc: 'Verstehen Sie Indiens Geschichte, Kultur und Traditionen ganz ohne Sprachbarrieren. Wählen Sie Ihre Sprache und lassen Sie sich von ItihAI leiten.',
    listen_learn_title: 'Hören & Lernen mit Sprachführern',
    demo_badge: 'Phase 2 UI-Vorschau',
  },
  es: {
    brand_name: 'ItihAI',
    tagline: 'Comprende el idioma, descubre la cultura',
    hero_subtitle: 'Tu compañero multilingüe inteligente para descubrir el patrimonio, la historia y las tradiciones de la India.',
    explore_heritage: 'Explorar Patrimonio',
    ask_itihai: 'Preguntar a ItihAI',
    start_journey: 'Comenzar el viaje',
    nav_home: 'Inicio',
    nav_explore: 'Explorar',
    nav_guide: 'Guía IA',
    nav_languages: 'Idiomas',
    nav_about: 'Acerca de',
    featured_title: 'Explora el patrimonio de la India',
    featured_subtitle: 'Descubre monumentos eternos, maravillas de la UNESCO y tradiciones milenarias.',
    how_it_works_title: 'Cómo funciona',
    how_step1: 'Descubrir',
    how_step1_desc: 'Explora monumentos por período histórico, estilo arquitectónico y región.',
    how_step2: 'Preguntar',
    how_step2_desc: 'Haz preguntas en tu idioma nativo por voz o texto.',
    how_step3: 'Comprender',
    how_step3_desc: 'Recibe información histórica verificada y normas de etiqueta cultural.',
    how_step4: 'Explorar',
    how_step4_desc: 'Sumérgete con narraciones de audio manos libres en cada sitio.',
    view_all_sites: 'Ver todos los sitios',
    search_placeholder: 'Buscar monumentos, ciudades, dinastías...',
    all_regions: 'Todas las regiones',
    all_periods: 'Todos los períodos',
    all_types: 'Todas las categorías',
    ask_about_monument: 'Preguntar a ItihAI sobre este lugar',
    listen_audio_guide: 'Escuchar narración de audio',
    facts_title: 'Datos fascinantes',
    traditions_title: 'Costumbres y etiqueta local',
    visiting_title: 'Guía práctica para visitantes',
    nearby_title: 'Atracciones cercanas',
    speak_your_lang_title: 'Explora la India en tu idioma',
    speak_your_lang_desc: 'Comprende la historia, la cultura y las tradiciones de la India sin barreras idiomáticas. Elige tu idioma y deja que ItihAI guíe tu viaje.',
    listen_learn_title: 'Escucha y aprende con audioguías',
    demo_badge: 'Vista previa UI Fase 2',
  },
  ja: {
    brand_name: 'ItihAI',
    tagline: '言葉を理解し、文化を発見する',
    hero_subtitle: 'インドの歴史、文化、世界遺産を深く知るための多言語AIガイド。',
    explore_heritage: '遺産を探索',
    ask_itihai: 'ItihAIに質問',
    start_journey: '旅を始める',
    nav_home: 'ホーム',
    nav_explore: '探索',
    nav_guide: 'AIガイド',
    nav_languages: '対応言語',
    nav_about: '概要',
    featured_title: 'インドの文化遺産を探索',
    featured_subtitle: '時代を超えた建造物、ユネスコ世界遺産、息づく伝統を発見しましょう。',
    how_it_works_title: '利用の流れ',
    how_step1: '探す',
    how_step1_desc: '歴史的時代、建築様式、地域ごとに名所を検索できます。',
    how_step2: '質問する',
    how_step2_desc: '母国語で音声またはテキストで気軽に質問できます。',
    how_step3: '理解する',
    how_step3_desc: '公的記録に基づく正確な歴史解説とマナー・エチケットを確認。',
    how_step4: '体験する',
    how_step4_desc: '現地で臨場感あふれる音声ガイドをお楽しみください。',
    view_all_sites: 'すべての遺産を見る',
    search_placeholder: '遺跡、都市、王朝を検索...',
    all_regions: 'すべての地域',
    all_periods: 'すべての時代',
    all_types: 'すべてのカテゴリー',
    ask_about_monument: 'この遺跡について質問する',
    listen_audio_guide: '音声ガイドを聴く',
    facts_title: '興味深い事実',
    traditions_title: '現地の習慣とエチケット',
    visiting_title: '観光ガイド・実用情報',
    nearby_title: '周辺の見どころ',
    speak_your_lang_title: 'あなたの言語でインドを旅しよう',
    speak_your_lang_desc: '言語の壁を感じることなく、インドの豊かな歴史、文化、伝統を深く理解できます。言語を選んで、ItihAIと共に素晴らしい旅へ。',
    listen_learn_title: '音声ガイドで学ぶ',
    demo_badge: 'Phase 2 プレビュー',
  },
  it: {
    brand_name: 'ItihAI',
    tagline: 'Comprendi la lingua, scopri la cultura',
    hero_subtitle: 'Il tuo compagno multilingue intelligente per scoprire il patrimonio, la storia e le tradizioni dell\'India.',
    explore_heritage: 'Esplora il patrimonio',
    ask_itihai: 'Chiedi a ItihAI',
    start_journey: 'Inizia il viaggio',
    nav_home: 'Home',
    nav_explore: 'Esplora',
    nav_guide: 'Guida IA',
    nav_languages: 'Lingue',
    nav_about: 'Chi siamo',
    featured_title: 'Esplora il patrimonio dell\'India',
    featured_subtitle: 'Scopri monumenti senza tempo, siti Patrimonio dell\'Umanità UNESCO e tradizioni millenarie.',
    how_it_works_title: 'Come funziona',
    how_step1: 'Scopri',
    how_step1_desc: 'Esplora i monumenti per periodo storico, stile architettonico e regione.',
    how_step2: 'Chiedi',
    how_step2_desc: 'Fai domande nella tua lingua madre tramite voce o testo.',
    how_step3: 'Comprendi',
    how_step3_desc: 'Ricevi approfondimenti storici verificati e regole di etichetta locale.',
    how_step4: 'Esplora',
    how_step4_desc: 'Immergiti nelle visite con narrazioni audio interattive sul posto.',
    view_all_sites: 'Visualizza tutti i siti',
    search_placeholder: 'Cerca monumenti, città, dinastie...',
    all_regions: 'Tutte le regioni',
    all_periods: 'Tutti i periodi',
    all_types: 'Tutte le categorie',
    ask_about_monument: 'Chiedi a ItihAI informazioni su questo luogo',
    listen_audio_guide: 'Ascolta la narrazione audio',
    facts_title: 'Curiosità storiche',
    traditions_title: 'Usi e tradizioni locali',
    visiting_title: 'Guida pratica per i visitatori',
    nearby_title: 'Attrazioni nelle vicinanze',
    speak_your_lang_title: 'Esplora l\'India nella tua lingua',
    speak_your_lang_desc: 'Comprendi la storia, la cultura e le tradizioni dell\'India senza barriere linguistiche. Scegli la tua lingua e lasciati guidare da ItihAI.',
    listen_learn_title: 'Ascolta e impara con le audioguide',
    demo_badge: 'Anteprima UI Fase 2',
  },
  hi: {
    brand_name: 'इतिहास-AI',
    tagline: 'भाषा को समझें, संस्कृति को जानें',
    hero_subtitle: 'भारत की समृद्ध विरासत, इतिहास और संस्कृति को जानने के लिए विदेशी पर्यटकों का बहुभाषी साथी।',
    explore_heritage: 'विरासत देखें',
    ask_itihai: 'इतिहास-AI से पूछें',
    start_journey: 'यात्रा शुरू करें',
    nav_home: 'होम',
    nav_explore: 'विरासत',
    nav_guide: 'एआई गाइड',
    nav_languages: 'भाषाएं',
    nav_about: 'परिचय',
    featured_title: 'भारत की अमूल्य धरोहर',
    featured_subtitle: 'यूनेस्को विश्व धरोहर स्थलों और जीवंत परंपराओं की खोज करें।',
    how_it_works_title: 'यह कैसे काम करता है',
    how_step1: 'खोजें',
    how_step1_desc: 'ऐतिहासिक काल, स्थापत्य कला और क्षेत्रों के आधार पर स्मारक खोजें।',
    how_step2: 'पूछें',
    how_step2_desc: 'अपनी भाषा में बोलकर या लिखकर सांस्कृतिक सवाल पूछें।',
    how_step3: 'समझें',
    how_step3_desc: 'सत्यापित इतिहास और स्थानीय रीति-रिवाजों की सटीक जानकारी पाएं।',
    how_step4: 'अनुभव करें',
    how_step4_desc: 'स्थल पर ऑडियो गाइड सुनकर इतिहास को जीवंत अनुभव करें।',
    view_all_sites: 'सभी धरोहर स्थल देखें',
    search_placeholder: 'स्मारक, शहर या राजवंश खोजें...',
    all_regions: 'सभी क्षेत्र',
    all_periods: 'सभी काल',
    all_types: 'सभी श्रेणियां',
    ask_about_monument: 'इस स्मारक के बारे में पूछें',
    listen_audio_guide: 'ऑडियो गाइड सुनें',
    facts_title: 'रोचक तथ्य',
    traditions_title: 'स्थानीय परंपराएं व नियम',
    visiting_title: 'यात्री मार्गदर्शन',
    nearby_title: 'आस-पास के दर्शनीय स्थल',
    speak_your_lang_title: 'अपनी भाषा में भारत की खोज करें',
    speak_your_lang_desc: 'बिना किसी भाषाई बाधा के भारत के इतिहास, संस्कृति और परंपराओं को समझें। अपनी भाषा चुनें और ItihAI को अपना मार्गदर्शक बनाएं।',
    listen_learn_title: 'ऑडियो गाइड से सीखें',
    demo_badge: 'फेज 2 पूर्वावलोकन',
  },
  bn: {
    brand_name: 'ইতিহাস-AI',
    tagline: 'ভাষা বুঝুন, সংস্কৃতি আবিষ্কার করুন',
    hero_subtitle: 'ভারতের ঐতিহ্য, ইতিহাস এবং সংস্কৃতি অন্বেষণের আপনার বুদ্ধিমান বহুভাষিক সঙ্গী।',
    explore_heritage: 'ঐতিহ্য দেখুন',
    ask_itihai: 'ইতিহাস-AI কে জিজ্ঞাসা করুন',
    start_journey: 'যাত্রা শুরু করুন',
    nav_home: 'হোম',
    nav_explore: 'ঐতিহ্য অন্বেষণ',
    nav_guide: 'এআই গাইড',
    nav_languages: 'ভাষা সমূহ',
    nav_about: 'আমাদের সম্পর্কে',
    featured_title: 'ভারতের সমৃদ্ধ ঐতিহ্য',
    featured_subtitle: 'ইউনেস্কো বিশ্ব ঐতিহ্য ও কালজয়ী স্থাপত্যের পরিচয় নিন।',
    how_it_works_title: 'এটি যেভাবে কাজ করে',
    how_step1: 'অনুসন্ধান',
    how_step1_desc: 'ঐতিহাসিক সময়কাল ও শৈলীর ভিত্তিতে সৌধসমূহ খুঁজুন।',
    how_step2: 'প্রশ্ন করুন',
    how_step2_desc: 'আপনার পছন্দের ভাষায় ভয়েস বা টেক্সটের মাধ্যমে প্রশ্ন করুন।',
    how_step3: 'অনুধাবন করুন',
    how_step3_desc: 'যাচাইকৃত ইতিহাস ও সাংস্কৃতিক শিষ্টাচারের নির্ভরযোগ্য তথ্য পান।',
    how_step4: 'উপভোগ করুন',
    how_step4_desc: 'অডিও নির্দেশনার সাথে সরাসরি স্মৃতিসৌধ পরিদর্শন করুন।',
    view_all_sites: 'সকল ঐতিহ্য স্থল দেখুন',
    search_placeholder: 'স্মৃতিসৌধ, শহর বা রাজবংশ খুঁজুন...',
    all_regions: 'সকল অঞ্চল',
    all_periods: 'সকল সময়কাল',
    all_types: 'সকল বিভাগ',
    ask_about_monument: 'এই স্থান সম্পর্কে জিজ্ঞাসা করুন',
    listen_audio_guide: 'অডিও গাইড শুনুন',
    facts_title: 'আকর্ষণীয় তথ্য',
    traditions_title: 'স্থানীয় প্রথা ও নিয়মাবলী',
    visiting_title: 'দর্শনার্থীদের ব্যবহারিক তথ্য',
    nearby_title: 'নিকটবর্তী আকর্ষণ',
    speak_your_lang_title: 'নিজের ভাষায় ভারত আবিষ্কার করুন',
    speak_your_lang_desc: 'ভাষার কোনো বাধা ছাড়াই ভারতের ইতিহাস, ঐতিহ্য ও সংস্কৃতি সহজে জানুন। আপনার ভাষা নির্বাচন করুন এবং ItihAI এর সাথে ভ্রমণ করুন।',
    listen_learn_title: 'শুনে ও জেনে ভ্রমণ করুন',
    demo_badge: 'ফেজ ২ প্রিভিউ',
  },
};

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState(() => {
    return localStorage.getItem('itihai_language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('itihai_language', currentLanguage);
    document.documentElement.lang = currentLanguage;
  }, [currentLanguage]);

  const t = (key) => {
    const langDict = UI_TRANSLATIONS[currentLanguage] || UI_TRANSLATIONS.en;
    return langDict[key] || UI_TRANSLATIONS.en[key] || key;
  };

  const getLanguageDetails = () => {
    return ACTIVE_LANGUAGES.find((l) => l.code === currentLanguage) || ACTIVE_LANGUAGES[0];
  };

  return (
    <LanguageContext.Provider
      value={{
        currentLanguage,
        setLanguage: setCurrentLanguage,
        t,
        getLanguageDetails,
        activeLanguages: ACTIVE_LANGUAGES,
        internationalLanguages: INTERNATIONAL_LANGUAGES,
        indianLanguages: INDIAN_LANGUAGES,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
