"""
Google Gemini AI Service Layer for ItihAI (Phase 5).
Connects to Google GenAI SDK for cultural, historical, and architectural narration.
"""

import logging
from typing import Optional

from app.core.config import settings

logger = logging.getLogger(__name__)

# ItihAI Cultural Guide System Instruction
ITIHAI_SYSTEM_INSTRUCTION = """You are ItihAI, an intelligent multilingual Indian heritage and cultural guide designed primarily for international and domestic tourists visiting India.

Your purpose is to explain Indian heritage landmarks, history, architecture, spiritual significance, visitor etiquette, and cultural traditions in warm, engaging, tourist-friendly language.

Core Principles:
1. Historical Integrity & Conservative Facts: Provide authentic historical knowledge. NEVER invent facts, rulers, dates, archaeological discoveries, or UNESCO/ASI classifications. If historical details are contested or unavailable, state the uncertainty transparently.
2. Cultural & Religious Sensitivity: Explain sacred traditions, temple sanctums, and local customs with utmost respect and cultural dignity.
3. Context Prioritization: When structured heritage landmark information is provided in the prompt, prioritize that verified information for answering questions about the landmark's architecture, history, traditions, and visiting rules.
4. No Fabrication: If the provided landmark context does not contain enough information to address a specific query, politely explain that the available archival record is limited and provide only general, cautious information without fabricating facts.
5. Multilingual Narration: Always formulate your response strictly in the requested target language:
   - "en" -> English
   - "hi" -> Hindi (हिंदी)
   - "bn" -> Bengali (বাংলা)
6. Tourist Experience: Never pretend to have physically visited the site; rather, speak as an expert digital cultural ambassador guiding a curious traveler.
"""


class GeminiAIService:
    """Service wrapper for Google Gemini LLM integration via google-genai SDK."""

    def __init__(self):
        self._client = None

    def _get_client(self):
        """Initializes and returns a cached genai.Client instance if GEMINI_API_KEY is configured."""
        api_key = settings.GEMINI_API_KEY.strip()
        if not api_key:
            return None

        if self._client is None:
            try:
                from google import genai

                self._client = genai.Client(api_key=api_key)
                logger.info("Google GenAI client initialized successfully.")
            except Exception as e:
                logger.error("Failed to initialize Google GenAI client: %s", e)
                return None

        return self._client

    def is_configured(self) -> bool:
        """Checks whether Gemini API key is configured."""
        return bool(settings.GEMINI_API_KEY and settings.GEMINI_API_KEY.strip())

    async def generate_response(
        self,
        message: str,
        language: str = "en",
        context: Optional[str] = None,
    ) -> str:
        """
        Generates a culturally grounded explanation for a user query using Gemini.

        Args:
            message: User query regarding Indian heritage or landmarks.
            language: Target response language code ('en', 'hi', 'bn').
            context: Optional structured PostgreSQL or knowledge base context.

        Returns:
            Clean response text generated by Gemini.
        """
        if not self.is_configured():
            logger.warning("AI chat request received, but GEMINI_API_KEY is not configured.")
            return (
                "AI service is not configured yet. Please configure the Gemini API key "
                "(GEMINI_API_KEY) in the backend environment."
            )

        client = self._get_client()
        if client is None:
            return "The AI guide is temporarily unavailable. Please verify backend AI configuration."

        # Map language codes to clear instructions
        lang_names = {
            "en": "English",
            "hi": "Hindi (हिंदी)",
            "bn": "Bengali (বাংলা)",
        }
        target_lang_label = lang_names.get(language, "English")

        # Construct prompt
        prompt_parts = []
        if context:
            prompt_parts.append(f"--- VERIFIED LANDMARK CONTEXT ---\n{context}\n---------------------------------")

        prompt_parts.append(
            f"User Question: {message}\n\n"
            f"Instruction: Please respond in {target_lang_label}. "
            f"Use the verified landmark context above when relevant to provide a concise, respectful, "
            f"and engaging explanation for the tourist."
        )

        full_prompt = "\n\n".join(prompt_parts)

        try:
            from google.genai import types

            logger.info("Sending request to Gemini model '%s' (language: %s)...", settings.GEMINI_MODEL, language)

            config = types.GenerateContentConfig(
                system_instruction=ITIHAI_SYSTEM_INSTRUCTION,
                temperature=settings.GEMINI_TEMPERATURE,
                max_output_tokens=settings.GEMINI_MAX_TOKENS,
            )

            response = client.models.generate_content(
                model=settings.GEMINI_MODEL,
                contents=full_prompt,
                config=config,
            )

            if response and response.text:
                logger.info("Gemini response generated successfully (%d characters).", len(response.text))
                return response.text.strip()
            else:
                logger.warning("Gemini returned empty response text.")
                return "I could not generate a response for this inquiry. Please try rephrasing your question."

        except Exception as e:
            error_str = str(e)
            logger.error("Gemini generation error: %s", error_str)

            # User-friendly error messaging without leaking sensitive credentials or stack traces
            if "RESOURCE_EXHAUSTED" in error_str or "429" in error_str:
                return "The AI guide has reached its rate limit. Please try again in a few moments."
            elif "DEADLINE_EXCEEDED" in error_str or "timed out" in error_str.lower():
                return "The request to the AI guide timed out. Please try again."
            elif "INVALID_ARGUMENT" in error_str or "API_KEY_INVALID" in error_str:
                return "AI guide authentication failed. Please check the backend Gemini API key configuration."
            else:
                return "The AI guide is temporarily unavailable. Please try again."


# Backward compatibility alias
AIService = GeminiAIService

# Global singleton instance
ai_service = GeminiAIService()
