"""
Pydantic schemas for ItihAI AI Guide service (Phase 5).
"""

from typing import Optional
from pydantic import BaseModel, Field


class AIChatRequest(BaseModel):
    """Request schema for ItihAI conversational AI guide."""

    message: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="Tourist query or inquiry regarding Indian heritage, monuments, history, or culture.",
        examples=["Why was the Taj Mahal built?"],
    )
    language: str = Field(
        default="en",
        pattern="^(en|hi|bn)$",
        description="Target response language code. Supported: en (English), hi (Hindi), bn (Bengali).",
        examples=["en"],
    )
    heritage_site_id: Optional[int] = Field(
        default=None,
        ge=1,
        description="Optional PostgreSQL heritage site ID to provide structured landmark context to the AI guide.",
        examples=[1],
    )


class AIChatResponse(BaseModel):
    """Response schema for ItihAI conversational AI guide."""

    response: str = Field(
        ...,
        description="Culturally grounded, historically conservative response generated by ItihAI guide.",
    )
    language: str = Field(
        default="en",
        description="Language code in which the response was generated.",
    )
    heritage_site_name: Optional[str] = Field(
        default=None,
        description="Name of the referenced heritage landmark, if context was supplied.",
    )
